DROP TABLE IF  EXISTS TB_DIRECCIONES;
CREATE TABLE TB_DIRECCIONES(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	calle VARCHAR (40) NOT NULL,
	localidad VARCHAR (40)NOT NULL,
	cp INTEGER (5) NOT NULL
);	


drop table IF  exists TB_BIBLIOTECAS;
CREATE TABLE TB_BIBLIOTECAS (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR (40) NOT NULL,
	fk_dir INTEGER NOT NULL,
	FOREIGN KEY (fk_dir) REFERENCES TB_DIRECCIONES (id)
);

drop table IF  exists TB_LIBROS;
CREATE TABLE TB_LIBROS(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR (40) NOT NULL,
	autor VARCHAR (40) NOT NULL,
	isbn NUMERIC (10) NOT NULL,
	fk_biblio INTEGER NOT NULL,
	FOREIGN KEY (fk_biblio) REFERENCES TB_BIBLIOTECAS (id)
);	

INSERT INTO TB_DIRECCIONES (calle,localidad,cp)
VALUES ("C/LABRADOR, 6", "NAVALCARNERO", 28600);
INSERT INTO TB_DIRECCIONES (calle,localidad,cp)
VALUES ("AVDA. ILUSTRACION, 25", "GETAFE", 28649);

INSERT INTO TB_BIBLIOTECAS (nombre,fk_dir)
VALUES ("BIBLIO1", 1);
INSERT INTO TB_BIBLIOTECAS (nombre,fk_dir)
VALUES ("BIBLIO2", 2);

INSERT INTO TB_LIBROS (titulo,autor,isbn,fk_biblio)
VALUES ("LIBRO1","AUTOR1", 11111111, 1);
INSERT INTO TB_LIBROS (titulo,autor,isbn,fk_biblio)
VALUES ("LIBRO2","AUTOR2", 222222222, 2);
INSERT INTO TB_LIBROS (titulo,autor,isbn,fk_biblio)
VALUES ("LIBRO3","AUTOR3", 33333333, 1);
INSERT INTO TB_LIBROS (titulo,autor,isbn,fk_biblio)
VALUES ("LIBRO4","AUTOR4", 44444444, 2);


SELECT * FROM TB_BIBLIOTECAS join  TB_DIRECCIONES using (id);

-- MOSTRAR EL NOMBRE Y TITULO DE UN LIBRO DE UNA BIBLIOTECA
SELECT titulo, autor FROM TB_LIBROS join TB_BIBLIOTECAS on (TB_LIBROS.fk_biblio =TB_BIBLIOTECAS.id)  WHERE TB_BIBLIOTECAS.id=1;
SELECT titulo, autor FROM TB_LIBROS join TB_BIBLIOTECAS where TB_LIBROS.fk_biblio = 2; -- lo repite 2 veces

-- MUESTRA TODOS LOS LIBROS CON SUS BIBLIOTECAS.
SELECT titulo, autor, nombre, calle, localidad FROM TB_LIBROS, TB_BIBLIOTECAS, TB_DIRECCIONES where TB_LIBROS.id=TB_BIBLIOTECAS.id and TB_DIRECCIONES.id=TB_BIBLIOTECAS.fk_dir; 
SELECT titulo, autor, nombre, calle, localidad FROM TB_LIBROS, TB_BIBLIOTECAS, TB_DIRECCIONES where TB_LIBROS.fk_biblio=TB_BIBLIOTECAS.id and TB_DIRECCIONES.id=TB_BIBLIOTECAS.fk_dir; 


-- MOSTRAR EL NOMBRE, TITULO DE UN LIBRO + NOMBRE Y DIRECCIÓN DE LA BIBLIOTECA DONDE ESTÁ EL LIBRO.
SELECT titulo, autor, nombre, calle, localidad FROM TB_LIBROS, TB_BIBLIOTECAS, TB_DIRECCIONES where TB_LIBROS.fk_biblio=1 and TB_BIBLIOTECAS.fk_dir=TB_DIRECCIONES.id and TB_LIBROS.fk_biblio=TB_BIBLIOTECAS.id;





-- DISTINTAS CONSULTAS
SELECT * FROM TB_LIBROS JOIN TB_BIBLIOTECAS USING (ID);
SELECT * FROM TB_DIRECCIONES;
SELECT * FROM TB_BIBLIOTECAS;