DROP TABLE IF EXISTS TB_DIRECCIONES;
CREATE TABLE TB_DIRECCIONES(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	calle VARCHAR (40) NOT NULL,
	localidad VARCHAR (40)NOT NULL,
	cp INTEGER (5) NOT NULL
);	


drop table IF exists TB_BIBLIOTECAS;
CREATE TABLE TB_BIBLIOTECAS (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR (40) NOT NULL,
	fk_dir INTEGER NOT NULL,
	FOREIGN KEY (fk_dir) REFERENCES TB_DIRECCIONES (id)
);

drop table IF exists TB_LIBROS;
CREATE TABLE TB_LIBROS(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	titulo VARCHAR (40) NOT NULL,
	autor VARCHAR (40) NOT NULL,
	isbn NUMERIC (10) NOT NULL,
	fk_biblio INTEGER NOT NULL,
	FOREIGN KEY (fk_biblio) REFERENCES TB_BIBLIOTECAS (id)
);	

INSERT INTO TB_DIRECCIONES (calle,localidad,cp)
VALUES ("C/LABRADOR, 6", "NAVALCARNERO", 28600);
INSERT INTO TB_DIRECCIONES (calle,localidad,cp)
VALUES ("AVDA. ILUSTRACION, 25", "GETAFE", 28649);

INSERT INTO TB_BIBLIOTECAS (nombre,fk_dir)
VALUES ("BIBLIO1", 1);
INSERT INTO TB_BIBLIOTECAS (nombre,fk_dir)
VALUES ("BIBLIO2", 2);

SELECT * FROM TB_BIBLIOTECAS;
SELECT * FROM TB_DIRECCIONES;