SELECT * FROM TB_GUERRERO;
UPDATE TB_GUERRERO set FUERZA=5, RESISTENCIA=6 where NOMBRE in ('GUERRERO 6','GUERRERO 7');
UPDATE TB_GUERRERO SET FUERZA=5, RESISTENCIA=6 WHERE NOMBRE ='GUERRERO 5';
UPDATE TB_GUERRERO SET FUERZA=9, RESISTENCIA=4 WHERE NOMBRE ='GUERRERO 10'; 

SELECT * FROM TB_GUERRERO WHERE VEHICULO_ID = 1
ORDER BY FUERZA DESC, RESISTENCIA DESC, NOMBRE ASC
LIMIT 5;